##  Triquintic Interpolation Algotrithm
### Kyle Bradach

#### Section 0

In [1]:
import numpy as np
import numpy.linalg as la

# Sympy is used for the symbolic expressions.
from sympy import *

####  Section 1: Creation of Polynomial Components

In [2]:
# Declaring Symbols for Sympy
x, y, z = symbols('x y z')    

#  List of Variable Interactions for creating the polynomial
variables = []  

# Empty list for storing index
index = []

degree = 5

#  Loop for Generating Variable Interaction
for k in range(0, degree + 1):                 # +1 because Python lists are shifted back so this corrects for it.
    for j in range(0, degree + 1):
        for i in range(0, degree + 1):
            variables.append( x**i * y**j * z**k )  #Variable factors
                    
            index.append(str(i) + str(j) + str(k))  #Index for Coeffs

# Coefficients
coeffs = ['a' + x for x in index]


In [3]:
print(coeffs)

['a000', 'a100', 'a200', 'a300', 'a400', 'a500', 'a010', 'a110', 'a210', 'a310', 'a410', 'a510', 'a020', 'a120', 'a220', 'a320', 'a420', 'a520', 'a030', 'a130', 'a230', 'a330', 'a430', 'a530', 'a040', 'a140', 'a240', 'a340', 'a440', 'a540', 'a050', 'a150', 'a250', 'a350', 'a450', 'a550', 'a001', 'a101', 'a201', 'a301', 'a401', 'a501', 'a011', 'a111', 'a211', 'a311', 'a411', 'a511', 'a021', 'a121', 'a221', 'a321', 'a421', 'a521', 'a031', 'a131', 'a231', 'a331', 'a431', 'a531', 'a041', 'a141', 'a241', 'a341', 'a441', 'a541', 'a051', 'a151', 'a251', 'a351', 'a451', 'a551', 'a002', 'a102', 'a202', 'a302', 'a402', 'a502', 'a012', 'a112', 'a212', 'a312', 'a412', 'a512', 'a022', 'a122', 'a222', 'a322', 'a422', 'a522', 'a032', 'a132', 'a232', 'a332', 'a432', 'a532', 'a042', 'a142', 'a242', 'a342', 'a442', 'a542', 'a052', 'a152', 'a252', 'a352', 'a452', 'a552', 'a003', 'a103', 'a203', 'a303', 'a403', 'a503', 'a013', 'a113', 'a213', 'a313', 'a413', 'a513', 'a023', 'a123', 'a223', 'a323', 'a423',

####  Section 2:  Construction of Polynomials

In [4]:
def create_polynomial(coeffiecients:list , variable_interactions:list):
    """
    Takes in a list of coeffecients and a list of variable interaction
    and assembles a polynomial that is the dot produce of the two.
    
    Converts the polynomial to an object compatible with Numpy.
    """
    # Create the polynomial using the dot product
    polynomial = Matrix([variable_interactions])* Transpose(Matrix([coeffiecients]))
    
    # Convert to Numpy
    return lambdify((x,y,z), expand(polynomial[0]),  modules='numpy')



def create_derivative(polynomial, variables:tuple):
    """
    Takes in the order 0 polynomial, and a tuple of variables in order of differentiation.
    
    Returns the derivative of the polynomial, that can be evaluated numerically.
    """
    # Differentiate and convert to evaluatable function.
    derivative = lambdify((x,y,z), (diff(polynomial, *variables)),  modules='numpy')

    return derivative  
    

In [5]:
# Construction of polynomials

#  Construction of Polynomial p(x,y,z)
p = create_polynomial(coeffs, variables)


###########################################
# Order 1
# x derivative
px = create_derivative(  p(x,y,z),   (x,)  )

# y derivative
py = create_derivative(p(x,y,z), (y,))

# z derivative
pz = create_derivative(p(x,y,z), (z,))


###########################################
# Order 2
# The xx derv
pxx = create_derivative(p(x,y,z), (x,x) )

# The xy derv
pxy = create_derivative(p(x,y,z), (x,y))

# The xz derv
pxz = create_derivative(p(x,y,z), (x,z))

# The yz derv
pyz = create_derivative(p(x,y,z), (y,z))

# The yy derv
pyy = create_derivative(p(x,y,z), (y,y))

# The zz derv
pzz = create_derivative(p(x,y,z), (z,z))


###########################################
# Order 3
# xxx derv
pxxx = create_derivative(p(x,y,z), (x,x,x))

# xxy derv
pxxy = create_derivative(p(x,y,z), (x,x,y))

# xxz derv
pxxz = create_derivative(p(x,y,z), (x,x,z))

# xyy derv
pxyy = create_derivative(p(x,y,z), (x,y,y))

# pxyz(x,y,z)  The xyz derv
pxyz = create_derivative(p(x,y,z), (x,y,z))

# xzz derv
pxzz = create_derivative(p(x,y,z), (x,z,z))

# yyy derv
pyyy = create_derivative(p(x,y,z), (y,y,y))

# yyz derv
pyyz = create_derivative(p(x,y,z), (y,y,z))

# yzz derv
pyzz = create_derivative(p(x,y,z), (y,z,z))

# zzz derv
pzzz = create_derivative(p(x,y,z), (z,z,z))


###########################################
# Order 4
# xxxx derv
pxxxx = create_derivative(p(x,y,z), (x,x,x,x))

# yyyy derv
pyyyy = create_derivative(p(x,y,z), (y,y,y,y))

# zzzz derv
pzzzz = create_derivative(p(x,y,z), (z,z,z,z))


# xxxy derv
pxxxy = create_derivative(p(x,y,z), (x,x,x,y))

# xxxz derv
pxxxz = create_derivative(p(x,y,z), (x,x,x,z))

# xyyy derv
pxyyy = create_derivative(p(x,y,z), (x,y,y,y))

# yyyz derv
pyyyz = create_derivative(p(x,y,z), (y,y,y,z))

# xzzz derv
pxzzz = create_derivative(p(x,y,z), (x,z,z,z))

# xxyy derv
pxxyy = create_derivative(p(x,y,z), (x,x,y,y))

# xxzz derv
pxxzz = create_derivative(p(x,y,z), (x,x,z,z))

# yyzz derv
pyyzz = create_derivative(p(x,y,z), (y,y,z,z))


# xyzz derv
pxyzz = create_derivative(p(x,y,z), (x,y,z,z))

# xyyz derv
pxyyz = create_derivative(p(x,y,z), (x,y,y,z))

# xxyz derv
pxxyz = create_derivative(p(x,y,z), (x,x,y,z))


###########################################
# Order 5
# xxyyz
pxxyyz = create_derivative(p(x,y,z), (x,x,y,y,z))

#xxyzz
pxxyzz = create_derivative(p(x,y,z), (x,x,y,z,z))

# xyyzz
pxyyzz = create_derivative(p(x,y,z), (x,y,y,z,z))


###########################################
# Order 6
#xxyyzz

pxxyyzz = create_derivative(p(x,y,z), (x,x,y,y,z,z))



#### All Polynomials are now in memory

In [6]:

py(0,1,0)




a010 + 2*a020 + 3*a030 + 4*a040 + 5*a050

####  Section 3:  Matrix Creation Functions  

In [7]:
# The Row creating function.  

#  Takes a function evaluated at a point, extracts coefficients
#  Combines everything from above into one process.

def rowcreate(polynomial)->list:
    """
    Takes in a polynomial evaluated at a point.
    
    Separates the numerical coefficients from the alpha coefficients.
    
    Returns a list of numerical coefficients which will later be a single row of the coefficient matrix.
    """
    # Convert the polynomial to string.
    polynomial = str(polynomial)
    
    # Separate the terms of the polynomial
    terms = polynomial.split('+')
    
    # Dictionary for storing alphas and the numeric coefficient.
    alphco = {}    
    for i in range(0,len(terms)):
        if '*' in terms[i]:     # Set dictionary entry to "a coeff" = value
            alphco[terms[i].split('*')[1].strip()] = float(terms[i].split('*')[0])
        else:
            alphco[terms[i].strip()] = 1
    
    # Row of zeros as template.
    row = [0] * len(variables)                  
    for key in alphco:   # Replace zeros with entries 
        row[coeffs.index(key)] = alphco[key]
        
    return row


#  Matrix Creation Function

def create_unfitted_matrix(function_names:list, points:list)->np.ndarray:
    """
    Takes in a list of a polynomial and its derivatives, as well as a list
    of the eight corners as tupules.
    
    Evaluates all the functions at all the corners, each of which gives us a 
    row of coefficients.
    
    Returns a Numpy matrix of coefficients which will later be solved.
    """
    #  The Matrix
    rows_list = []
    
    # We evaluate the polynomial and its derivatives across the eight corners.
    # We then create the row of coefficients for the matrix.
    for f in function_names: 
        for point in points:
            rows_list.append(rowcreate(f(*point)))
           
    # Take the list of rows of coefficients and create the matrix.
    return np.array(rows_list)


#  Matrix Inspection Function
def matrix_inspect(matrix)->bool:
    """
    Prints info about the matrix.
    
    Returns True if the system has one unique solution.
    """
    print(matrix)

    print('\n The dimensions of the matrix are: ',  np.shape(matrix))

    print('\n Rank: ', la.matrix_rank(matrix))
    
    if (np.shape(matrix)[0]==la.matrix_rank(matrix)) & (np.shape(matrix)[1]==la.matrix_rank(matrix)):
        return True
    
    else: 
        return False
    

#### Mesh Size Parameters:  Choosing where we pin down the function.

In [8]:
# The eight outer corners of the unit cube.
unit_cube = [(k, j, i)  for i in [0,1] for j in [0,1] for k in [0,1]]

In [9]:
unit_cube

[(0, 0, 0),
 (1, 0, 0),
 (0, 1, 0),
 (1, 1, 0),
 (0, 0, 1),
 (1, 0, 1),
 (0, 1, 1),
 (1, 1, 1)]

In [10]:
# Lists of possible functions

# Order followed by a number indicates all function present.

order_zero_one_two = [p, px, py, pz, pxx, pxy, pxz, pyy, pyz, pzz]  # Length 10


order_three_ex = [pxxy, pxxz, pxyy, pxyz, pyyz, pxzz, pyzz]     # Length 7,     Ex triplets of one variable.

order_four_ex = [pxxyy, pxxzz, pyyzz, pxxyz, pxyyz, pxyzz]      # Length 6

order_five_ex = [pxxyyz, pxxyzz, pxyyzz]                       # Length 3

order_six_ex = [pxxyyzz]                                      # Length 1



In [11]:
# Creation of Matrix

set_polynomials = order_zero_one_two + order_three_ex + order_four_ex + order_five_ex + order_six_ex 

set_polynomials_matrix = create_unfitted_matrix(set_polynomials, unit_cube).astype(int)

matrix_inspect(set_polynomials_matrix)


[[   1    0    0 ...    0    0    0]
 [   1    1    1 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ... 2400 4800 8000]]

 The dimensions of the matrix are:  (216, 216)

 Rank:  216


True

#### Testing Section

In [12]:
#  Test Function number 1

def f(x,y,z):
    return exp(-(x**2 + y**2 + z**2))    # e^-(x^2 + y^2 + z^2)

    
###########################################
# Order 1
# x derivative
fx = create_derivative(f(x,y,z), (x,))

# y derivative
fy = create_derivative(f(x,y,z), (y,))

# z derivative
fz = create_derivative(f(x,y,z), (z,))


###########################################
# Order 2
# The xx derv
fxx = create_derivative(f(x,y,z), (x,x))

# The xy derv
fxy = create_derivative(f(x,y,z), (x,y))

# The xz derv
fxz = create_derivative(f(x,y,z), (x,z))

# The yz derv
fyz = create_derivative(f(x,y,z), (y,z))

# The yy derv
fyy = create_derivative(f(x,y,z), (y,y))

# The zz derv
fzz = create_derivative(f(x,y,z), (z,z))


###########################################
# Order 3
# xxx derv
fxxx = create_derivative(f(x,y,z), (x,x,x))

# xxy derv
fxxy = create_derivative(f(x,y,z), (x,x,y))

# xxz derv
fxxz = create_derivative(f(x,y,z), (x,x,z))

# xyy derv
fxyy = create_derivative(f(x,y,z), (x,y,y))

# pxyz(x,y,z)  The xyz derv
fxyz = create_derivative(f(x,y,z), (x,y,z))

# xzz derv
fxzz = create_derivative(f(x,y,z), (x,z,z))

# yyy derv
fyyy = create_derivative(f(x,y,z), (y,y,y))

# yyz derv
fyyz = create_derivative(f(x,y,z), (y,y,z))

# yzz derv
fyzz = create_derivative(f(x,y,z), (y,z,z))

# zzz derv
fzzz = create_derivative(f(x,y,z), (z,z,z))


###########################################
# Order 4
# xxxx derv
fxxxx = create_derivative(f(x,y,z), (x,x,x,x))

# yyyy derv
fyyyy = create_derivative(f(x,y,z), (y,y,y,y))

# zzzz derv
fzzzz = create_derivative(f(x,y,z), (z,z,z,z))


# xxxy derv
fxxxy = create_derivative(f(x,y,z), (x,x,x,y))

# xxxz derv
fxxxz = create_derivative(f(x,y,z), (x,x,x,z))

# xyyy derv
fxyyy = create_derivative(f(x,y,z), (x,y,y,y))

# yyyz derv
fyyyz = create_derivative(f(x,y,z), (y,y,y,z))

# xzzz derv
fxzzz = create_derivative(f(x,y,z), (x,z,z,z))

# xxyy derv
fxxyy = create_derivative(f(x,y,z), (x,x,y,y))

# xxzz derv
fxxzz = create_derivative(f(x,y,z), (x,x,z,z))

# yyzz derv
fyyzz = create_derivative(f(x,y,z), (y,y,z,z))


# xyzz derv
fxyzz = create_derivative(f(x,y,z), (x,y,z,z))

# xyyz derv
fxyyz = create_derivative(f(x,y,z), (x,y,y,z))

# xxyz derv
fxxyz = create_derivative(f(x,y,z), (x,x,y,z))


###########################################
# Order 5
# xxyyz
fxxyyz = create_derivative(f(x,y,z), (x,x,y,y,z))

#xxyzz
fxxyzz = create_derivative(f(x,y,z), (x,x,y,z,z))

# xyyzz
fxyyzz = create_derivative(f(x,y,z), (x,y,y,z,z))


###########################################
# Order 6
#xxyyzz

fxxyyzz = create_derivative(f(x,y,z), (x,x,y,y,z,z))



# Test Function Lists

test_order_zero_one_two = [f, fx, fy, fz, fxx, fxy, fxz, fyy, fyz, fzz]  # Length 10

test_order_three_ex = [fxxy, fxxz, fxyy, fxyz, fyyz, fxzz, fyzz]     # Length 7,     

test_order_four_ex = [fxxyy, fxxzz, fyyzz, fxxyz, fxyyz, fxyzz]      # Length 6

test_order_five_ex = [fxxyyz, fxxyzz, fxyyzz]                       # Length 3

test_order_six_ex = [fxxyyzz]                                      # Length 1




# Norm 1
def norm1(vector):
    y = 0
    for i in vector:
        y += abs(i)
    return y

# Norm 2
def norm2(vector):
    y = 0
    for i in vector:
        y += i**2
    return y**0.5


#### Secton 4: Arbitrary Parallelepiped and Box input

In [13]:
def get_box_function():
    """
    Takes in 2 x-coords, 2 y-coords, and 2 z-coords from the user.
    
    Returns a list of the 8 points that form the box and a list
    of the delta's for each coordinate.
    """ 
    # Empty list for storing user input.
    xcoords = []
    ycoords = []
    zcoords = []
    
    # Is the box the unit cube?  Or are we using an arbitrary box?
    is_cube = input('Is sample box the unit cube?  (y/n)')
    
    if is_cube == 'y':
        xcoords = [0, 1]
        ycoords = [0, 1]
        zcoords = [0, 1]
        
        
    if is_cube == 'n':
        # Gather user input. Store them in list.
        xcoords.append(float(input('Enter the first x coordinate')))
        xcoords.append(float(input('Enter the second x coordinate')))

        ycoords.append(float(input('Enter the first y coordinate')))
        ycoords.append(float(input('Enter the second y coordinate')))

        zcoords.append(float(input('Enter the first z coordinate')))
        zcoords.append(float(input('Enter the second z coordinate')))
    
    if (is_cube != 'y') & (is_cube != 'n'):
        raise Exception('Please input y/n to declare that the unit cube is being used.')
    
    # Compute the range in each coordinate as delta_variable.
    x_delta = max(xcoords) - min(xcoords)
    y_delta = max(ycoords) - min(ycoords)
    z_delta = max(zcoords) - min(zcoords)
    
    deltas = [x_delta, y_delta, z_delta]
    
    # Generate all 8 points.
    points_list = [ (i, j, k) for k in zcoords for j in ycoords for i in xcoords]
        
    return points_list, deltas, min(xcoords), min(ycoords), min(zcoords)
    

#### Assign box paramters  

In [ ]:
test_box, deltas, xmin, ymin, zmin = get_box_function()

# Create the function for transformation.
def to_cube(x, y, z):
    """
    Takes in an (x,y,z) tuple from any place in the coordinate system and applies the to_cube trasnformation which
    maps the sample box to the unit cube.
    """
    xnew = (x - xmin)/deltas[0]
    ynew = (y - ymin)/deltas[1]
    znew = (z - zmin)/deltas[2]
    
    return (xnew, ynew, znew)
    

#### Functions to use and their tuple of variables that they are derivatives for.  To be used in the transformed box version.

In [ ]:
# Case 2 dictionary.

set_functions_dict = {   f:(), fx:(x,), fy:(y,), fz:(z,), fxx:(x,x), fxy:(x,y), fxz:(x,z), fyy:(y,y), fyz:(y,z), fzz:(z,z),  # Orders 0-2, Length 10
                fxxy:(x,x,y), fxxz:(x,x,z), fxyy:(x,y,y), fxyz:(x,y,z), fyyz:(y,y,z), fxzz:(x,z,z), fyzz:(y,z,z),    # Length 7,   3rd order  Ex triplets of one variable.
                fxxyy:(x,x,y,y), fxxzz:(x,x,z,z), fyyzz:(y,y,z,z), fxxyz:(x,x,y,z), fxyyz:(x,y,y,z), fxyzz:(x,y,z,z),    # Order 4,  Length 6
                fxxyyz:(x,x,y,y,z), fxxyzz:(x,x,y,z,z), fxyyzz:(x,y,y,z,z),                     # Order 5, Length 3
                fxxyyzz:(x,x,y,y,z,z)}                                 # Length 1



def delta_scalar(variables:tuple, deltas:list)->float:
    """
    Takes in a tuple of variables and a list of deltas for each variable.
    
    Returns the product of the delta scalars based on the tuple of variables.
    """
    scalar = 1
    
    for i in variables:
        
        if i==x:
            scalar *= deltas[0]  # use delta x
        
        if i==y:
            scalar *= deltas[1]
        
        if i==z:
            scalar *= deltas[2]
    
    return scalar    



def get_fitted_coeffs(matrix, functions_dict:dict, test_box:list)->list:
    """
    Takes in the matrix for the unfitted polynomial, the list of sample functions (RHS).
    
    Scales the derivatives and solves the system
    
    matrix * alpha_coeffs = delta scalars * RHS
    
    for the alpha coefficients.  Returns the list of fitted alpha coefficients.
    """
    
    # We evaluate the test function and its derivatives at the eight corners.
    #  We then form the RHS vector for our linear system.
    rhs = np.array([ delta_scalar(variables, deltas) * f(*corner) for f, variables in functions_dict.items() for corner in test_box ], dtype='float')

    #  Solving the system for the Values of Alpha coefficients
    fitted_alpha_coefficients = la.solve(matrix, rhs)
    
    return fitted_alpha_coefficients


new_alpha_coeffs = get_fitted_coeffs(set_polynomials_matrix, set_functions_dict, test_box)


####  Section 5:  Construction of the fitted polynomials.

In [ ]:
#  Construction of Polynomial p(x,y)

def fit_p(x,y,z):
    preimage_polynomial = create_polynomial(new_alpha_coeffs, variables)
    
    return preimage_polynomial(*to_cube(x,y,z))


# px(x,y,z)
fit_px = create_derivative(fit_p(x,y,z), (x,))

# p(x,y,z) y derivative
fit_py = create_derivative(fit_p(x,y,z), (y,))

# p(x,y,z) z derivative
fit_pz = create_derivative(fit_p(x,y,z), (z,))

# pxy(x,y,z)  The xy derv
fit_pxy = create_derivative(fit_p(x,y,z), (x,y))

# pxz(x,y,z)  The xz derv
fit_pxz = create_derivative(fit_p(x,y,z), (x,z))

# pyz(x,y,z)  The yz derv
fit_pyz = create_derivative(fit_p(x,y,z), (y,z))

# pxx(x,y,z)  The xx derv
fit_pxx = create_derivative(fit_p(x,y,z), (x,x))



# pzz(x,y,z)  The zz derv
fit_pzz = create_derivative(fit_p(x,y,z), (z,z))

# pzzz(x,y,z)  The zzz derv
fit_pzzz = create_derivative(fit_p(x,y,z), (z,z,z))




# pxyz(x,y,z)  The xyz derv
fit_pxyz = create_derivative(fit_p(x,y,z), (x,y,z))



# pxyzz(x,y,z)  The xyz derv
fit_pxyzz = create_derivative(fit_p(x,y,z), (x,y,z,z))


In [ ]:
# Actual

f(.8, .2, .1)

In [ ]:
# Estimate

fit_p(.8, .2, .1)

#### Sample points for testing

In [ ]:
test_points = [(0.5, 0.25, 0.25), (0.4, 0.8, 0.1),
               (0.5, 0.5, 0.25), (0.8, 0.9, 0.7)]

#  Estimates and Error.

# Actual values for test function number 1.
actual_f1_values = np.array([ f(*point) for point in test_points])

# Estimated values from our fitted polynomial.
estimated_values = np.array([ fit_p(*point) for point in test_points])

# Error vector.
error_f1 = actual_f1_values - estimated_values


print('The 1-norm of the error vector is: ',norm1(error_f1), '\n')

print('The 2-norm of the error vector is: ', norm2(error_f1), '\n')